language: node_js
node_js:
- '0.10'
before_install:
- npm install -g gulp
after_success:
- node deploy/deploy.js
notifications:
  hipchat:
    rooms:
      secure: EIKrGFfzRDvzMfAjMtR4kpd5cpUj/nA/QporBta55pyW75r5kaBns3EMUUfcq5l5kN9aflIMZevKwSHnaZwMRnPY3vY/e1nRDBJhJhK+1J5xXOyVQ17B1JtworCkciiNdrb38O0mNpmY4xjR9PwPawPdD6jBrDlDFrc6zvyB+74=
    template:
    - '<a href="%{build_url}">%{branch}</a> - <a href="%{compare_url}">%{commit}</a>
      : %{message}'
    format: html
env:
  global:
  - secure: C3ns4bIP1h9PzP127HeXTdIFWLshNj6CQENyT1BUWxmRFYfRHWQHTLXhYtw9Clv42L+kehoEA6Lak4hyNQXa0J26d4skum0YHVycIoS90bE96TN5I3NYSTWJI61lou0cl+D1kByrTIqr1jZxomGNGF+xWmxcwaXIwTntegPPwnQ=
  - secure: mswog/W9YCauQbjUA9FCjwP/WkH3mV5QPPcQHOG4CgaT70UXeYeKJPol+oNimBe4jzmsrmd8emsZHvD2sW2pIbrX9v1ZIUZwUH++R1z+EiqvP31sed/CcpEiUH5s1dMnQ/lTFmvTP0ILBFFe7X1NYmicT11rhrvGRGV55Ps37Rw=
  - secure: pA+rzOGsqTh1SEQKdKP1FqC5P0NhO2G/PA1EOMS1/KK94I7jwj64ayzVDjiD2NvhyjGltOwLc+Rl0SsHTJ589zFbRqXnEneZCp8sO9cSE/5LdF8fu96OlBPLUbd150++E/8stJuWP+TM7zE9biBfe0DQK8hHC4XccoTxhLFW3k8=
  - secure: S+TTNB1Fa3wV4e1StMbwYSoV1BKkQw8M++wUtPSAP0ELSZPilOGBS/zXbf3us9WgRv9TDopm3QnHpfWj5HB2MeptQHkngxyjTs9WgVMzJjJi/AyTOFSrYbZ6t9qGQ09olXhSGNB9W74P6jHcbUoPqdRjf6wD7oaj0cuGcziCW20=
